name: Deploy Stable

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Add n64 toolchain
      uses: myci-actions/add-deb-repo@10
      with:
        repo: deb http://practicerom.com/public/packages/debian staging main
        repo-name: practicerom
        keys-asc: https://practicerom.com/public/packages/debian/pgp.pub
    - name: Install deps
      run: |
        sudo apt-get install n64-ultra
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Build
      run: |
        ./deploy.sh stable
    - name: Deploy to Netlify
      uses: netlify/actions/cli@master
      with:
        args: deploy --prod --dir=dist
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_STABLE }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
