name: Continuous Integration Workflow

on: [push, pull_request, workflow_dispatch]

jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Use cached node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm i

  test:
    needs: deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Use cached node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm i

      - name: Use cached node_modules cache dir
        uses: actions/cache@v3
        with:
          path: node_modules/.cache
          key: ${{ runner.os }}-node-cache-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-node-cache-

      - name: Test
        run: npm test
#  deploy:
#    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
#    needs: test
#    runs-on: ubuntu-latest
#    steps:
#     - name: Deploy
#       uses: actions/github-script@v6
#       with:
#         github-token: ${{ secrets.PAT_TOKEN }}
#         script: |
#          await github.rest.actions.createWorkflowDispatch({
#            owner: 'OoTMM',
#            repo: 'gui',
#            workflow_id: 'dev.yml',
#            ref: 'develop'
#          })
#  deploy-stable:
#    if: ${{ github.event_name == 'push' && contains(github.ref, 'refs/tags/') }}
#    needs: test
#    runs-on: ubuntu-latest
#    steps:
#     - name: Deploy
#       uses: actions/github-script@v6
#       with:
#         github-token: ${{ secrets.PAT_TOKEN }}
#         script: |
#          await github.rest.actions.createWorkflowDispatch({
#            owner: 'OoTMM',
#            repo: 'gui',
#            workflow_id: 'stable.yml',
#            ref: 'master'
#          })
#
