name: Deploy Web Generator

on:
  push:
    branches: [ "develop" ]

jobs:
  deploy-generator:
    runs-on: ubuntu-latest
    steps:
     - name: Deploy
       uses: actions/github-script@v6
       with:
         github-token: ${{ secrets.PAT_TOKEN }}
         script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'OoTMM',
            repo: 'gui',
            workflow_id: 'ootmm.yml',
            ref: 'master'
          })
